<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Pack_commission extends MY_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Pack_commission_model');
    }

    /*
     * Listing of pack_commission
     */

    function index() {
        $data['pack_commission'] = $this->Pack_commission_model->get_all_pack_commission();

        $this->load->view('pack_commission/index', $data);
    }

    /*
     * Adding a new pack_commission
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $pack = $this->input->post('pack');
            $comm = $this->input->post('comm');
            $comm_type = $this->input->post('comm_type');
            $code = $this->input->post('ser_code');

            
            for($i=0; $i<count($code); $i++) {
                
                    $selected = $comm_type[$i];

                    if ($selected == 1) {
                        $params = array(
//               
                            'is_percent' => $selected,
                            'comm_per' => $comm[$i],
                            'fixedaoumt' => 0,
                        );
                    } elseif ($selected == 2) {
                        $params = array(
//               
                            'is_percent' => $selected,
                            'comm_per' => 0,
                            'fixedaoumt' => $comm[$i],
                        );
                    }
                    
//                    var_dump($params);
//                    echo $code[$i];
//                    exit();
                    $pack_commission_id = $this->Pack_commission_model->update_pack_commission($pack, $code[$i], $params);
                
            }

//            var_dump($params);

            redirect("Admin/Packages/{$pack}");
        } else {
            $this->load->view('pack_commission/add');
        }
    }

    /*
     * Editing a pack_commission
     */

    function edit($pk_id) {
        // check if the pack_commission exists before trying to edit it
        $data['pack_commission'] = $this->Pack_commission_model->get_pack_commission($pk_id);

        if (isset($data['pack_commission']['pk_id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'pack_id' => $this->input->post('pack_id'),
                    'ser_code' => $this->input->post('ser_code'),
                    'is_percent' => $this->input->post('is_percent'),
                    'comm_per' => $this->input->post('comm_per'),
                    'fixedaoumt' => $this->input->post('fixedaoumt'),
                );

                $this->Pack_commission_model->update_pack_commission($pk_id, $params);
                redirect('pack_commission/index');
            } else {
                $this->load->view('pack_commission/edit', $data);
            }
        } else
            show_error('The pack_commission you are trying to edit does not exist.');
    }

}
