<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Service extends MY_Controller {

    public $userdetails;
    public $type;

    function __construct() {
        parent::__construct();
        $this->load->model('Service_model');
        $this->load->model('Category_model');
        $this->load->model('Pack_commission_model');
        $this->load->model('Package_model');

        $this->userdetails = $this->GetDetails();
        $this->type = $this->userdetails['type'];
        $this->data['uinfo'] = $this->userdetails;
    }

    /*
     * Listing of services
     */

    function add_service() {
        if ($this->type == ADMIN) {
            $cat = $this->Category_model->get_all_categories();
            $this->data['cats'] = $cat;
            $this->body = "admin/adnewservice";
            $this->ShowView($this->type);
        } else {
            redirect('Account/LogOut');
        }
    }

    /*
     * Adding a new service
     */

    function add() {
        if ($this->type == ADMIN) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'ser_code' => strtoupper($this->input->post('scode')),
                    'ser_name' => $this->input->post('sname'),
                    'cat_id' => $this->input->post('cat'),
                    'api_code' => $this->input->post('apicode'),
                    'api_comm' => $this->input->post('apicomm'),
                );

                $service_id = $this->Service_model->add_service($params);
                $pack = $this->Package_model->get_all_packages();
                if (is_array($pack)) {
                    foreach ($pack as $value) {
                        $comm = array(
                            'pack_id' => $value['pack_id'],
                            'ser_code' => $params['ser_code'],
                            'is_percent' => 1,
                            'comm_per' => 0,
                            'fixedaoumt' => 0,
                        );

                        $this->Pack_commission_model->add_pack_commission($comm);
                    }
                }
                redirect('Admin/Services');
            } else {
                redirect('Admin/Services');
            }
        }
    }

    /*
     * Editing a service
     */

    function edit() {
        // check if the service exists before trying to edit it
        $code = $this->input->post('scode');
        $data['service'] = $this->Service_model->get_service($code);

        if (isset($data['service']['ser_code'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'ser_name' => $this->input->post('sname'),
                    'ser_status' => $this->input->post('status'),
                    'api_code' => $this->input->post('apicode'),
                    'api_comm' => $this->input->post('apicomm'),
                );

                $this->Service_model->update_service($code, $params);
                redirect("Admin/Services/{$code}");
            } else {
                $data['_view'] = 'service/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The service you are trying to edit does not exist.');
    }

}
