<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class User extends MY_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->model('Account_model');
    }

    /*
     * Listing of users
     */

    function index() {
        $data['users'] = $this->User_model->get_all_users();

        $data['_view'] = 'user/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new user
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'us_name' => $this->input->post('us_name'),
                'us_email' => $this->input->post('us_email'),
                'us_phone' => $this->input->post('us_phone'),
                'created' => $this->input->post('created'),
            );

            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        } else {
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a user
     */

    function edit($us_id) {
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($us_id);

        if (isset($data['user']['us_id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'us_name' => $this->input->post('us_name'),
                    'us_email' => $this->input->post('us_email'),
                    'us_phone' => $this->input->post('us_phone'),
                    'created' => $this->input->post('created'),
                );

                $this->User_model->update_user($us_id, $params);
                redirect('user/index');
            } else {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The user you are trying to edit does not exist.');
    }

    public function GetUserInfo() {
        if (isset($_POST) && count($_POST) > 0) {
//            var_dump($_POST);

            $ph = $this->input->post('phone');
            $amt = $this->input->post('amt');
//            $userinfo = $this->User_model->GetUserByPhone($ph);
            $data = array('acc_username' => $ph, 'acc_type' => VENDOR);
            $user_acc = $this->Account_model->get_account_any($data);

            
            if (is_array($user_acc) && count($user_acc) > 0) {
                $userid = $user_acc['us_id'];
                $user = $this->User_model->get_user($userid, VENDOR);
                if (is_array($user)) {
                    $other = array('amount' => $amt);
                    $result = array_merge($other, $user);
                    $data['udet'] = $result;
                    $vw = $this->load->view('vendor/transfer_confirm', $data, TRUE);
                    echo $vw;
                }
            }

//            var_dump($data);
        }
    }

}
