<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class Wallet extends MY_Controller {

    public $userdetails;
    private $type;

    function __construct() {
        parent::__construct();
        $this->load->model('Wallet_model');
        $this->load->model('Topup_wallet_model');

//        if (isset($_SESSION['userdetails'])) {
//            $this->utype = VENDOR;
//            $this->userdetails = $_SESSION['userdetails'];
//        } elseif (isset($_SESSION['admindetails'])) {
//            $this->utype = ADMIN;
//            $this->userdetails = $_SESSION['admindetails'];
//        } else {
//            redirect('/');
//        }
        
         $this->userdetails = $this->GetDetails();
        $this->data['balance'] = $this->Wallet_model->Balance($this->userdetails['id']);
//        

        $this->data['uinfo'] = $this->userdetails;
    }

    /*
     * Listing of wallets
     */

    function index() {
        if ($this->utype == VENDOR) {
//            get the account balance 
            
//            get all the topup of this vendor
        } elseif ($this->utype == ADMIN) {
            
        }
    }

    /*
     * Adding a new wallet
     */

    function add() {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'us_id' => $this->input->post('us_id'),
                'balance' => $this->input->post('balance'),
                'wal_date' => $this->input->post('wal_date'),
            );


            $wallet_id = $this->Wallet_model->add_wallet($params);
            redirect('wallet/index');
        } else {
            $data['_view'] = 'wallet/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a wallet
     */

    function Topup() {
        // check if the wallet exists before trying to edit it

        $user = $this->GetDetails();

        if (isset($_POST) && count($_POST) > 0) {
            if ($this->type == VENDOR) {
                $balance = $this->Wallet_model->Balance($this->input->post('vendor'));
                $sbalance = $this->Wallet_model->Balance($user['id']);

                if ($sbalance >= $this->input->post('famt')) {


                    $newbalance = $balance + $this->input->post('famt');
                    $newsbal = $sbalance - $this->input->post('famt');
                    $params = array(
//					'us_id' => $this->input->post('vendor'),
                        'balance' => $newbalance,
                        'wal_date' => date('Y-m-d H:i:s'),
                    );
                    $sparams = array(
//					'us_id' => $this->input->post('vendor'),
                        'balance' => $newsbal,
                        'wal_date' => date('Y-m-d H:i:s'),
                    );
                    if ($this->Wallet_model->update_wallet($this->input->post('vendor'), $params)) {
                        $topup = array(
                            'us_id' => $this->input->post('vendor'),
                            'amount' => $this->input->post('famt'),
                            'created' => date('Y-m-d H:i:s'),
                            'tp_status' => 1,
                            'tp_from' => $user['id']
                        );


                        $this->Topup_wallet_model->add_topup_wallet($topup);

                        $this->Wallet_model->update_wallet($user['id'], $sparams);

                        redirect('Vendor/Transfer/1');
                    }
                } else {
                    redirect('Vendor/Transfer/0');
                }
            } elseif ($this->type == ADMIN) {
                $balance = $this->Wallet_model->Balance($this->input->post('vendor'));
                $newbalance = $this->input->post('famt') + $balance;
                $params = array(
//					'us_id' => $this->input->post('vendor'),
                    'balance' => $newbalance,
                    'wal_date' => date('Y-m-d H:i:s'),
                );

                if ($this->Wallet_model->update_wallet($this->input->post('vendor'), $params)) {
                    $topup = array(
                        'us_id' => $this->input->post('vendor'),
                        'amount' => $this->input->post('famt'),
                        'created' => date('Y-m-d H:i:s'),
                        'tp_status' => 1,
                        'tp_from' => 0
                    );

                    $this->Topup_wallet_model->add_topup_wallet($topup);
                }

                redirect('Admin/Vendors');
            }
        } else {
            redirect('Admin/Vendors');
        }
    }

}
