<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by cat_id
     */
    function get_category($cat_id)
    {
        return $this->db->get_where('categories',array('cat_id'=>$cat_id))->row_array();
    }
    
    /*
     * Get all categories
     */
    function get_all_categories()
    {
        return $this->db->get('categories')->result_array();
    }
    
    /*
     * function to add new category
     */
    function add_category($params)
    {
        $this->db->insert('categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update category
     */
    function update_category($cat_id,$params)
    {
        $this->db->where('cat_id',$cat_id);
        $response = $this->db->update('categories',$params);
        if($response)
        {
            return "category updated successfully";
        }
        else
        {
            return "Error occuring while updating category";
        }
    }
    
    /*
     * function to delete category
     */
    function delete_category($cat_id)
    {
        $response = $this->db->delete('categories',array('cat_id'=>$cat_id));
        if($response)
        {
            return "category deleted successfully";
        }
        else
        {
            return "Error occuring while deleting category";
        }
    }
}
