<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Databundle_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get category by cat_id
     */
    function get_databundle($d_id)
    {
        return $this->db->get_where('databundles',array('id'=>$d_id))->row_array();
    }

    function get_databundle_service($ser_code)
    {
        return $this->db->get_where('databundles',array('ser_code'=>$ser_code))->result_array();
    }
    
    /*
     * Get all categories
     */
    function get_all_databundle()
    {
        return $this->db->get('databundles')->result_array();
    }
    
    /*
     * function to add new category
     */
    function add_databundle($params)
    {
        $this->db->insert('databundles',$params);
        return $this->db->insert_id();
    }
    
    function add_databundle_bulk($params)
    {
        $this->db->insert_batch('databundles',$params);
        return $this->db->insert_id();
    }
    /*
     * function to update category
     */
    function update_databundle($cat_id,$params)
    {
        $this->db->where('cat_id',$cat_id);
        $response = $this->db->update('databundles',$params);
        if($response)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    /*
     * function to delete category
     */
    function delete_databundle($d_id)
    {
        $response = $this->db->delete('databundles',array('id'=>$d_id));
        if($response)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}
