<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Service_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get service by ser_code
     */
    function get_service($ser_code)
    {
        return $this->db->get_where('services',array('ser_code'=>$ser_code))->row_array();
    }
    function get_service_category($cat)
    {
        return $this->db->get_where('services',array('cat_id'=>$cat))->result_array();
    }
    
    /*
     * Get all services
     */
    function get_all_services()
    {
        return $this->db->get('services')->result_array();
    }
    
    /*
     * function to add new service
     */
    function add_service($params)
    {
        $this->db->insert('services',$params);
        return $this->db->insert_id();
    }

    function add_services($params)
    {
        try{
        $this->db->insert_batch('services',$params);
        return true;
        }
        catch(Exception $ex){
            return false;
        }
        
    }
    
    /*
     * function to update service
     */
    function update_service($ser_code,$params)
    {
        $this->db->where('ser_code',$ser_code);
        $response = $this->db->update('services',$params);
        if($response)
        {
            return "service updated successfully";
        }
        else
        {
            return "Error occuring while updating service";
        }
    }
    
    /*
     * function to delete service
     */
    function delete_service($ser_code)
    {
        $response = $this->db->delete('services',array('ser_code'=>$ser_code));
        if($response)
        {
            return "service deleted successfully";
        }
        else
        {
            return "Error occuring while deleting service";
        }
    }
}
