<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Topup_wallet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get topup_wallet by tp_id
     */
    function get_topup_wallet_vendor($tp_id)
    {
        return $this->db->get_where('topup_wallets',array('us_id'=>$tp_id))->result_array();
    }
    
    /*
     * Get all topup_wallets
     */
    function get_all_topup_wallets()
    {
        $this->db->select();
        $this->db->from('topup_wallets');
        $this->db->join('users','users.us_id=topup_wallets.us_id');
        $this->db->order_by('tp_id', 'DESC');
        $result = $this->db->get();
        $qy = $result->result_array();
        return $qy;
//        return $this->db->get('topup_wallets')->order_by('tp_id','desc')->result_array();
    }
    
    /*
     * function to add new topup_wallet
     */
    function add_topup_wallet($params)
    {
        $this->db->insert('topup_wallets',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update topup_wallet
     */
    function update_topup_wallet($tp_id,$params)
    {
        $this->db->where('tp_id',$tp_id);
        $response = $this->db->update('topup_wallets',$params);
        if($response)
        {
            return "topup_wallet updated successfully";
        }
        else
        {
            return "Error occuring while updating topup_wallet";
        }
    }
    
    /*
     * function to delete topup_wallet
     */
    function delete_topup_wallet($tp_id)
    {
        $response = $this->db->delete('topup_wallets',array('tp_id'=>$tp_id));
        if($response)
        {
            return "topup_wallet deleted successfully";
        }
        else
        {
            return "Error occuring while deleting topup_wallet";
        }
    }
}
