<?php

/*
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */

class User_model extends CI_Model {

    function __construct() {
        parent::__construct();
        $this->load->database();
    }

    /*
     * Get user by us_id
     */

    function get_user($us_id,$type) {
        $this->db->select();
        $this->db->from('users');
        $this->db->where('users.us_id', $us_id);
//            
        $this->db->where('acc_type', $type);
//        $this->db->or_where('acc_type', ADMIN);
        $this->db->join('accounts', 'users.us_id=accounts.us_id', 'LEFT');
        $this->db->join('wallets', 'users.us_id=wallets.us_id', 'LEFT');
        $this->db->order_by('users.us_id', 'desc');
        $this->db->limit(1);

        $query = $this->db->get()->row_array();
//            var_dump($query);
//            exit();
        return $query;
    }

    function GetUserByPhone($phone) {
        $this->db->select();
        $this->db->from('users');
        $this->db->where('us_phone', $phone);
//            
//            $this->db->where('acc_ps', $this->Hash($pass));
//        $this->db->join('accounts', 'users.us_id=accounts.us_id', 'LEFT');
        $this->db->join('wallets', 'users.us_id=wallets.us_id', 'LEFT');
//             $this->db->order_by('users.us_id','desc');
        $this->db->limit(1);

        $query = $this->db->get()->row_array();
//            var_dump($query);
//            exit();
        return $query;
    }

    /*
     * Get all users
     */

    function get_all_users() {
//        return $this->db
//                ->order_by('us_id','desc')
//                ->limit(100)
//                ->get('users')
//                              
//                ->result_array();

        $this->db->select();
        $this->db->from('users');
        $this->db->where('acc_type', VENDOR);
//            
//            $this->db->where('acc_ps', $this->Hash($pass));
        $this->db->join('accounts', 'users.us_id=accounts.us_id', 'LEFT');
        $this->db->join('wallets', 'users.us_id=wallets.us_id', 'LEFT');
        $this->db->order_by('users.us_id', 'desc');
//            $this->db->limit(100);

        $query = $this->db->get()->result_array();
//            var_dump($query);
//            exit();
        return $query;
    }

    /*
     * function to add new user
     */

    function add_user($params) {
        $this->db->insert('users', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update user
     */

    function update_user($us_id, $params) {
        $this->db->where('us_id', $us_id);
        $response = $this->db->update('users', $params);
        if ($response) {
            return "user updated successfully";
        } else {
            return "Error occuring while updating user";
        }
    }

    /*
     * function to delete user
     */

    function delete_user($us_id) {
        $response = $this->db->delete('users', array('us_id' => $us_id));
        if ($response) {
            return "user deleted successfully";
        } else {
            return "Error occuring while deleting user";
        }
    }

    public function CheckRegister($phone) {
        $where = "us_phone='{$phone}'";
        $result = $this->db->get_where('users', $where)->row_array();

        if (count($result)) {
            return TRUE;
        }

        return FALSE;
    }

}
