<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Wallet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get wallet by wal_id
     */
    function Balance($us_id)
    {
       $wallet = $this->db->get_where('wallets',array('us_id'=>$us_id))->row_array();
       if($wallet !=NULL){
           return $wallet['balance'];
       }
           
       return FALSE;
    }
    
    /*
     * Get all wallets
     */
    function get_all_wallets()
    {
        return $this->db->get('wallets')->result_array();
    }
    
    /*
     * function to add new wallet
     */
    function add_wallet($params)
    {
        $this->db->insert('wallets',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update wallet
     */
    function update_wallet($us_id,$params)
    {
        $this->db->where('us_id',$us_id);
        $response = $this->db->update('wallets',$params);
        if($response)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    /*
     * function to delete wallet
     */
    function delete_wallet($wal_id)
    {
        $response = $this->db->delete('wallets',array('wal_id'=>$wal_id));
        if($response)
        {
            return "wallet deleted successfully";
        }
        else
        {
            return "Error occuring while deleting wallet";
        }
    }
}
